worker_processes 1;

events {
    worker_connections 1024;
}

stream {
    upstream backend {
        server docker_container_0:18883;
        server docker_container_1:18883;
#        least_conn;         # least_conn or roundrobin, hash $remote_addr; etc.
    }

    server {
        listen 18883;
        proxy_pass backend;
        proxy_timeout 300s;
    }
}
